language: python

python:
  - "2.7"
  - "3.2"
  - "pypy"

install:
  - pip install -r requirements.txt --use-mirrors

script:
  - export PYTHONPATH=$PYTHONPATH:.
  - py.test

after_success:
  - coveralls
